const RECIPES_DATA = [
	{
		id: 2,
		img: '/img/recipes/cheeseburger.png',
		title: 'Big and Juicy Wagyu Beef Cheeseburger',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '30 Minutes',
		type: 'Snack',
	},
	{
		id: 3,
		img: '/img/recipes/fish.png',
		title: 'Fresh Lime Roasted Salmon with Ginger Sauce',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '30 Minutes',
		type: 'Fish',
	},
	{
		id: 4,
		img: '/img/recipes/pancake.png',
		title: 'Strawberry Oatmeal Pancake with Honey Syrup',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '25 Minutes',
		type: 'Breakfast',
	},
	{
		id: 5,
		img: '/img/recipes/salad.png',
		title: 'Fresh and Healthy Mixed Mayonnaise Salad',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '15 Minutes',
		type: 'Healthy',
	},
	{
		id: 6,
		img: '/img/recipes/meatball.png',
		title: 'Chicken Meatballs with Cream Cheese',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '45 Minutes',
		type: 'Meat',
	},
	{
		id: 2,
		img: '/img/recipes/fruity-pancake.png',
		title: 'Fruity Pancake with Orange & Blueberry',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '30 Minutes',
		type: 'Sweet',
	},
	{
		id: 2,
		img: '/img/recipes/one-pot-chicken.png',
		title: 'The Best Easy One Pot Chicken and Rice',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '25 Minutes',
		type: 'Main Dish',
	},
	{
		id: 2,
		img: '/img/recipes/creamy-chicken-bacon-pasta.png',
		title: 'The Creamiest Creamy Chicken and Bacon Pasta',
		desc: 'Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut enim ',
		time: '55 Minutes',
		type: 'Noodles',
	},
];

export default RECIPES_DATA;
